apiVersion: v1
data:
  grafana-admin-password: bGFiaW90
kind: Secret
metadata:
  labels:
    io.kompose.service: grafana-admin-password
  name: grafana-admin-password
  namespace: tcp-ip
type: Opaque
