version: '3'

services:
  emqx:
    image: emqx:5.6.1
    container_name: emqx
    environment:
      - EMQX_NODE_NAME=emqx@node1.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER_STATIC_SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTH__PASSWORD_HASH=plain
      - EMQX_AUTH__MYSQL_SERVER=mysql:3306
      - EMQX_AUTH__MYSQL_USERNAME=root
      - EMQX_AUTH__MYSQL_PASSWORD=459907
      - EMQX_AUTH__MYSQL_DATABASE=mqtt_user
      - EMQX_AUTH__MYSQL_QUERY=SELECT username, password_hash FROM mqtt_user;
      - EMQX_AUTH__MYSQL_POOL_SIZE=8
    networks:
      - mi_red
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

    depends_on:
      - mysql  
        
    volumes:
      - ./data:/data
    

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - mi_red
    volumes:
      - ./data:/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 459907 
      MYSQL_DATABASE: mqtt_user
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mi_red

networks:
  mi_red:
    external: true
