apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: streamlit
  name: streamlit
  namespace: tcp-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/server-default: "true"
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: INFLUXDB_BUCKET
              value: iotdata
            - name: INFLUXDB_ORG
              value: labiot2024
            - name: INFLUXDB_TOKEN
              value: labtcpip-iotdata-auth-token
            - name: INFLUXDB_URL
              value: http://influxdb:8086
          image: federodriguez16/sensor:latest
          name: streamlit
          ports:
            - containerPort: 8501
              hostPort: 8501
              protocol: TCP
      restartPolicy: Always
