apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: tcp-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/server-default: "true"
        io.kompose.service: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
          hostPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "labiot2024"
        - name: MYSQL_DATABASE
          value: "emqx_auth"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-claim0
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: mysql-cm1
          subPath: init.sql
      restartPolicy: Always
      volumes:
      - name: mysql-claim0
        persistentVolumeClaim:
          claimName: mysql-claim0
      - name: mysql-cm1
        configMap:
          name: mysql-cm1

