apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: telegraf-claim1
  name: telegraf-claim1
  namespace: tcp-ip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
