site_name: Proyecto Final Integrador

nav:
  - Home: index.md
  - Sobre este proyecto: about.md
  - Empezando: getting_started.md
  - Servidor:
    - Introduccion: intro_server.md
    - Docker Compose: docker.md
    - Telegraf: telegraf.md
    - Seguridad EMQX: conf_seguridad.md
    - Influx DB: influxdb.md
    - Grafana: grafana.md
    - Streamlit: Streamlit.md
  - Clientes:
    - Sonoff: sonoff.md
    - Raspberry: raspy.md
    - DHT11: dht11.md
  
theme: readthedocs