apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: emqx-claim0
  name: emqx-claim0
  namespace: tcp-ip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
