version: "3.9"
services:
  emqx:
    user: root
    build: ./emqx
    ports:
      - "18083:18083"
      - "1883:1883"
    volumes:
      - ./emqx/data/data:/opt/emqx/data
      - ./emqx/data/log:/opt/emqx/log
      #- ./emqx/config/emqx_auth_mysql.conf:/opt/emqx/etc/plugins/emqx_auth_mysql.conf

  influxdb:
    build: ./influxdb
    ports: 
      - "8086:8086"
    volumes:
      - ./influxdb/data/data:/var/lib/influxdb2
      - ./influxdb/data/config:/etc/influxdb2
  
  telegraf:
    build: ./telegraf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 20
    volumes:
      - ./telegraf/data/telegraf.conf:/etc/telegraf/telegraf.conf

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    user: root
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    secrets:
      - source: grafana_admin_password
        target: /run/secrets/admin_password
    
secrets:
  grafana_admin_password:
    file: ./grafana/secrets/grafana_admin_password