version: "3.9"
services:
  emqx:
    user: root
    build: ./emqx
    ports:
      - "18083:18083"
      - "1883:1883"
    volumes:
      - ./emqx/data/data:/opt/emqx/data
      - ./emqx/data/log:/opt/emqx/log
      #- ./emqx/config/emqx_auth_mysql.conf:/opt/emqx/etc/plugins/emqx_auth_mysql.conf
    network_mode: "host"

  influxdb:
    build: ./influxdb
    ports: 
      - "8086:8086"
    volumes:
      - ./influxdb/data/data:/var/lib/influxdb2
      - ./influxdb/data/config:/etc/influxdb2
    network_mode: "host"

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"

  grafana:
    user: root
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    secrets:
      - source: grafana_admin_password
        target: /run/secrets/admin_password
    network_mode: "host"

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
    network_mode: "host"

secrets:
  grafana_admin_password:
    file: ./grafana/secrets/grafana_admin_password
