site_name: Proyecto Final Integrador

nav:
  - Home: index.md
  - Sobre este proyecto: about.md
  - Empezando: getting_started.md
  - Servidor:
    - Introduccion: intro_server.md
    - Telegraf: telegraf.md
    - Influx DB: influxdb.md
    - Grafana: grafana.md
  - Clientes:
    - Sonoff: sonoff.md
  
theme: readthedocs